### ISSUE TITLE
User memasuki halaman pertama website

### ISSUE THREAD

**Issue by IamBara** [FTP-YCAB-Fullstack/GP1-RGB-White#17]
Di dalam website terdapat 

- [x] background #4  

- [x] sebuah deskripsi singkat mengenai ColorTravel #5 

- [x] button navigasi explore #7 

- [x] sebuah video singkat dari youtube mengenai indonesia #8 

- [x] sebuah image button contact us untuk menghubungi pihak ColorTravel #10 

- [x] sebuah text "About us" #9
