### ISSUE TITLE
User memasuki halaman ke dua website

### ISSUE THREAD

**Issue by renitanathania** [FTP-YCAB-Fullstack/GP1-RGB-White#18]
pada saat memasuki halaman ini, terdapat

- [x] dua text link menuju halaman lain #11 
- [x] Background website #4 
- [x] kolom pencarian destinasi #12 
- [x] Hasil yang ditampilkan #13 
- [x] Contact us #10
